const mongoose = require('mongoose');
const Product = require('./models/Product');
require('dotenv').config();

mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/electronox', {
  useNewUrlParser: true,
  useUnifiedTopology: true,
}).then(() => {
  console.log('✓ MongoDB connected for seeding');
  seedDatabase();
}).catch(err => {
  console.error('MongoDB connection error:', err);
  process.exit(1);
});

const products = [
  {
    name: 'iPhone 15 Pro Max',
    price: 1199,
    originalPrice: 1299,
    category: 'Smartphones',
    description: 'Latest flagship smartphone with advanced camera and processor',
    image: 'https://images.unsplash.com/photo-1592286927505-1ae2f8790937?w=400&h=400&fit=crop',
    rating: 4.8,
    reviews: 342,
    inStock: true,
    isFeatured: true,
    isDeals: true,
    discount: 8,
  },
  {
    name: 'Samsung Galaxy S24 Ultra',
    price: 1299,
    originalPrice: 1399,
    category: 'Smartphones',
    description: 'Powerful Android flagship with stunning display',
    image: 'https://images.unsplash.com/photo-1511707267537-b85faf00021e?w=400&h=400&fit=crop',
    rating: 4.7,
    reviews: 289,
    inStock: true,
    isFeatured: true,
    isDeals: false,
    discount: 7,
  },
  {
    name: 'MacBook Pro 16" M3',
    price: 3499,
    originalPrice: 3699,
    category: 'Laptops',
    description: 'Professional laptop with M3 Max chip and exceptional performance',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&h=400&fit=crop',
    rating: 4.9,
    reviews: 256,
    inStock: true,
    isFeatured: true,
    isDeals: true,
    discount: 5,
  },
  {
    name: 'Dell XPS 15',
    price: 2299,
    originalPrice: 2499,
    category: 'Laptops',
    description: 'High-performance Windows laptop for creators',
    image: 'https://images.unsplash.com/photo-1588872657840-790ff3bde08c?w=400&h=400&fit=crop',
    rating: 4.6,
    reviews: 198,
    inStock: true,
    isFeatured: true,
    isDeals: false,
    discount: 8,
  },
  {
    name: 'LG OLED 55" TV',
    price: 1899,
    originalPrice: 2199,
    category: 'Smart TVs',
    description: '4K OLED display with exceptional color and contrast',
    image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b3f7?w=400&h=400&fit=crop',
    rating: 4.8,
    reviews: 421,
    inStock: true,
    isFeatured: true,
    isDeals: true,
    discount: 13,
  },
  {
    name: 'Sony WH-1000XM5 Headphones',
    price: 399,
    originalPrice: 449,
    category: 'Audio',
    description: 'Premium noise-canceling wireless headphones',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop',
    rating: 4.7,
    reviews: 512,
    inStock: true,
    isFeatured: true,
    isDeals: false,
    discount: 11,
  },
  {
    name: 'PlayStation 5',
    price: 499,
    originalPrice: 599,
    category: 'Gaming',
    description: 'Next-gen gaming console with stunning graphics',
    image: 'https://images.unsplash.com/photo-1607107104079-5c0b4ddc36eb?w=400&h=400&fit=crop',
    rating: 4.9,
    reviews: 789,
    inStock: true,
    isFeatured: true,
    isDeals: true,
    discount: 16,
  },
  {
    name: 'Xbox Series X',
    price: 499,
    originalPrice: 599,
    category: 'Gaming',
    description: 'High-performance gaming console with Game Pass',
    image: 'https://images.unsplash.com/photo-1605559424843-9e4c3ca4b7f1?w=400&h=400&fit=crop',
    rating: 4.8,
    reviews: 654,
    inStock: true,
    isFeatured: false,
    isDeals: false,
    discount: 16,
  },
  {
    name: 'Amazon Echo Show 15',
    price: 249,
    originalPrice: 349,
    category: 'Smart Home',
    description: 'Large smart display for your home',
    image: 'https://images.unsplash.com/photo-1589003077984-894e133dabab?w=400&h=400&fit=crop',
    rating: 4.5,
    reviews: 234,
    inStock: true,
    isFeatured: true,
    isDeals: true,
    discount: 28,
  },
  {
    name: 'Smart Home Hub Bundle',
    price: 299,
    originalPrice: 399,
    category: 'Smart Home',
    description: 'Complete smart home automation package',
    image: 'https://images.unsplash.com/photo-1558089120-d27b525cda1d?w=400&h=400&fit=crop',
    rating: 4.4,
    reviews: 156,
    inStock: true,
    isFeatured: false,
    isDeals: false,
    discount: 25,
  },
  {
    name: 'Apple AirPods Max',
    price: 549,
    originalPrice: 649,
    category: 'Audio',
    description: 'Premium spatial audio headphones with immersive sound',
    image: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400&h=400&fit=crop',
    rating: 4.6,
    reviews: 387,
    inStock: true,
    isFeatured: false,
    isDeals: true,
    discount: 15,
  },
  {
    name: 'USB-C Fast Charger 65W',
    price: 39,
    originalPrice: 59,
    category: 'Accessories',
    description: 'Universal fast charging solution for all devices',
    image: 'https://images.unsplash.com/photo-1591336696925-8340a1201b98?w=400&h=400&fit=crop',
    rating: 4.7,
    reviews: 823,
    inStock: true,
    isFeatured: true,
    isDeals: false,
    discount: 33,
  },
  {
    name: 'Wireless Phone Stand',
    price: 29,
    originalPrice: 49,
    category: 'Accessories',
    description: 'Adjustable stand with wireless charging',
    image: 'https://images.unsplash.com/photo-1587829191301-dc798b83add3?w=400&h=400&fit=crop',
    rating: 4.4,
    reviews: 267,
    inStock: true,
    isFeatured: true,
    isDeals: false,
    discount: 40,
  },
  {
    name: 'Google Pixel 8 Pro',
    price: 999,
    originalPrice: 1099,
    category: 'Smartphones',
    description: 'AI-powered smartphone with exceptional photography',
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&h=400&fit=crop',
    rating: 4.7,
    reviews: 278,
    inStock: true,
    isFeatured: false,
    isDeals: true,
    discount: 9,
  },
  {
    name: 'Lenovo ThinkPad X1 Carbon',
    price: 1899,
    originalPrice: 2199,
    category: 'Laptops',
    description: 'Business-class ultrabook with premium build quality',
    image: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=400&h=400&fit=crop',
    rating: 4.6,
    reviews: 145,
    inStock: true,
    isFeatured: false,
    isDeals: false,
    discount: 13,
  },
  {
    name: 'Samsung 65" 4K TV',
    price: 1299,
    originalPrice: 1599,
    category: 'Smart TVs',
    description: 'Vibrant QLED display with smart features',
    image: 'https://images.unsplash.com/photo-1522869635100-ce306400e29d?w=400&h=400&fit=crop',
    rating: 4.5,
    reviews: 302,
    inStock: true,
    isFeatured: false,
    isDeals: true,
    discount: 18,
  },
  {
    name: 'Bose QuietComfort Earbuds',
    price: 299,
    originalPrice: 379,
    category: 'Audio',
    description: 'True wireless earbuds with superior noise cancellation',
    image: 'https://images.unsplash.com/photo-1572533534303-d2c7f91b92b2?w=400&h=400&fit=crop',
    rating: 4.6,
    reviews: 445,
    inStock: true,
    isFeatured: false,
    isDeals: false,
    discount: 21,
  },
  {
    name: 'Nintendo Switch Pro',
    price: 349,
    originalPrice: 449,
    category: 'Gaming',
    description: 'Portable gaming console with versatile play styles',
    image: 'https://images.unsplash.com/photo-1606841837239-c5a1a4a07af7?w=400&h=400&fit=crop',
    rating: 4.7,
    reviews: 567,
    inStock: true,
    isFeatured: false,
    isDeals: true,
    discount: 22,
  },
  {
    name: 'Philips Smart Bulb Kit',
    price: 149,
    originalPrice: 199,
    category: 'Smart Home',
    description: '16 million colors smart lighting system',
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&h=400&fit=crop',
    rating: 4.5,
    reviews: 289,
    inStock: true,
    isFeatured: true,
    isDeals: false,
    discount: 25,
  },
  {
    name: 'Anker Power Bank 30000mAh',
    price: 59,
    originalPrice: 99,
    category: 'Accessories',
    description: 'High-capacity portable charger with fast charging',
    image: 'https://images.unsplash.com/photo-1591290621149-bcf1f4f8f9df?w=400&h=400&fit=crop',
    rating: 4.8,
    reviews: 934,
    inStock: true,
    isFeatured: false,
    isDeals: false,
    discount: 40,
  },
  {
    name: 'GoPro Hero 12 Black',
    price: 499,
    originalPrice: 599,
    category: 'Accessories',
    description: 'Professional action camera with 5.3K video',
    image: 'https://images.unsplash.com/photo-1617638924702-92f37fcb133d?w=400&h=400&fit=crop',
    rating: 4.7,
    reviews: 412,
    inStock: true,
    isFeatured: true,
    isDeals: true,
    discount: 16,
  },
  {
    name: 'OnePlus 12 5G',
    price: 799,
    originalPrice: 899,
    category: 'Smartphones',
    description: 'Fast flagship with 120Hz display',
    image: 'https://images.unsplash.com/photo-1611532736579-6b16e2b50449?w=400&h=400&fit=crop',
    rating: 4.6,
    reviews: 256,
    inStock: true,
    isFeatured: false,
    isDeals: false,
    discount: 11,
  },
  {
    name: 'Asus ROG Gaming Laptop',
    price: 2199,
    originalPrice: 2799,
    category: 'Laptops',
    description: 'High-performance gaming laptop with RTX 4080',
    image: 'https://images.unsplash.com/photo-1588872657840-790ff3bde08c?w=400&h=400&fit=crop',
    rating: 4.8,
    reviews: 523,
    inStock: true,
    isFeatured: true,
    isDeals: true,
    discount: 21,
  },
];

async function seedDatabase() {
  try {
    await Product.deleteMany({});
    console.log('✓ Cleared existing products');

    const createdProducts = await Product.insertMany(products);
    console.log(`✓ Created ${createdProducts.length} products`);
    console.log('✓ Seeding completed successfully');
    
    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
}
